name: run-tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11.6
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.6
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
          pip install -r requirements.txt
      
      - name: Run unit test
        run: |
          pytest --cov=app --cov-report=html
          